//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesLib.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;UI&gt;
        ///
        ///  &lt;Modul&gt;
        ///    &lt;ModulNum&gt;1&lt;/ModulNum&gt;
        ///    &lt;ModulName&gt;学生信息管理&lt;/ModulName&gt;
        ///  &lt;/Modul&gt;
        ///  &lt;Modul&gt;
        ///    &lt;ModulNum&gt;2&lt;/ModulNum&gt;
        ///    &lt;ModulName&gt;教师信息管理&lt;/ModulName&gt;
        ///  &lt;/Modul&gt;
        ///  &lt;Modul&gt;
        ///    &lt;ModulNum&gt;3&lt;/ModulNum&gt;
        ///    &lt;ModulName&gt;成绩管理&lt;/ModulName&gt;
        ///  &lt;/Modul&gt;
        ///  &lt;Modul&gt;
        ///    &lt;ModulNum&gt;4&lt;/ModulNum&gt;
        ///    &lt;ModulName&gt;课程管理&lt;/ModulName&gt;
        ///  &lt;/Modul&gt;
        ///  &lt;Modul&gt;
        ///    &lt;ModulNum&gt;5&lt;/ModulNum&gt;
        ///    &lt;ModulName&gt;教师授课管理&lt;/ModulName&gt;
        ///  &lt;/Modul&gt;
        ///  &lt;Modul&gt;
        ///    &lt;Modul [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UI_XML {
            get {
                return ResourceManager.GetString("UI_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;UI&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot; xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:appinfo source=&quot;urn:schemas-microsoft-com:xml-msdatasource&quot;&gt;
        ///      &lt;DataSource DefaultConnectionIndex=&quot;0&quot; FunctionsComponentName=&quot;QueriesTableAdapter&quot; Modifier=&quot;AutoLayout, AnsiClass, Class, Public&quot; SchemaSerializationMode=&quot;IncludeSchema&quot; xmlns=&quot;urn:schemas-microsof [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UI_XSD {
            get {
                return ResourceManager.GetString("UI_XSD", resourceCulture);
            }
        }
    }
}
